import json
import os
from pathlib import Path

from openai import OpenAI


DECISION_PATH = Path(
    "data/processed/decision_object.json"
)


def load_decision_context() -> dict:
    if not DECISION_PATH.exists():
        raise FileNotFoundError(
            "decision_object.json not found. "
            "Run the Narrate IQ pipeline first."
        )

    with DECISION_PATH.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def build_prompt(
    question: str,
    context: dict,
) -> str:

    context_json = json.dumps(
        context,
        indent=2,
        ensure_ascii=False,
    )

    return f"""
You are the Narrate IQ Business Intelligence Assistant.

Answer the user's question using ONLY the supplied
Narrate IQ analysis context.

You have access to:
- KPI results
- leading hypothesis
- evidence validation
- root-cause segments
- recommendations
- experiments
- historical learning
- business context

USER QUESTION:
{question}

NARRATE IQ CONTEXT:
{context_json}

Rules:

1. Never invent business facts, metrics, events,
   causes, recommendations, or experiment outcomes.

2. Use the exact numbers from the context.

3. Clearly distinguish evidence from causation.
   Do not claim something caused an outcome unless
   the context explicitly establishes causality.

4. When evidence is weak, explicitly say that it is weak.

5. When comparing hypotheses, compare their actual
   confidence and validation evidence.

6. When asked what to do, use the recommendation
   already generated by Narrate IQ where appropriate.

7. When asked about an experiment, use the experiment
   baseline, observed value, measured change, threshold,
   and outcome.

8. When information is unavailable, say:
   "That information is not available in the current
   Narrate IQ analysis."

9. Keep the response executive-friendly and concise.

10. Prefer this structure when useful:

What happened?
Why?
Where?
What should we do?
What did we learn?
"""


def ask_narrate_iq(
    question: str,
) -> str:

    question = question.strip()

    if not question:
        return "Please enter a business question."

    context = load_decision_context()

    api_key = os.getenv(
        "OPENAI_API_KEY"
    )

    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not configured."
        )

    model = os.getenv(
        "OPENAI_MODEL",
        "gpt-5-mini",
    )

    client = OpenAI(
        api_key=api_key
    )

    response = client.responses.create(
        model=model,
        instructions=(
            "You are the Narrate IQ evidence-grounded "
            "business intelligence assistant."
        ),
        input=build_prompt(
            question,
            context,
        ),
    )

    return response.output_text