from pathlib import Path
import shutil


PROJECT_ROOT = Path(__file__).resolve().parent.parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"


# Files that are generated by the intelligence pipeline.
GENERATED_FILES = [
    "daily_kpis.csv",
    "anomalies.csv",
    "revenue_driver_ranking.csv",
    "driver_attribution.csv",
    "confidence_scores.csv",
    "hypotheses.csv",
    "evidence_validation.csv",
    "recommendations.csv",
    "root_cause_graph.csv",
    "experiments.csv",
    "experiment_history.csv",
    "hypothesis_history.csv",
    "decision_object.json",
    "business_narrative.txt",
    "event_context.csv",
    "sales_dimension_drilldown.csv",
]


def reset_processed_outputs() -> None:
    PROCESSED_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    for filename in GENERATED_FILES:

        path = PROCESSED_DIR / filename

        if path.exists():
            path.unlink()


def available_datasets() -> dict[str, bool]:
    return {
        "sales": (
            RAW_DIR / "sales.csv"
        ).exists(),
        "inventory": (
            RAW_DIR / "inventory.csv"
        ).exists(),
        "marketing": (
            RAW_DIR / "marketing.csv"
        ).exists(),
        "events": (
            RAW_DIR / "business_events.csv"
        ).exists(),
    }


def validate_core_dataset() -> None:
    datasets = available_datasets()

    if not datasets["sales"]:
        raise FileNotFoundError(
            "sales.csv is required to run Narrate IQ."
        )